export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT = 'FETCH_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
